# Read values from environment
# settings moved to application.properties
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.continue-on-error=false

#-------------------------------------------------------
spring.datasource.hikari.data-source-properties.useUnicode=true
spring.datasource.hikari.data-source-properties.characterEncoding=UTF-8

#SLL connection properties
#### hosting server on railway.app is handling HTTPS by its own, so only "server.port" property is needed
#spring.ssl.bundle.pem.mybundle.keystore.certificate=${PRIVATE_KEY}
#spring.ssl.bundle.pem.mybundle.keystore.private-key=${CERTIFICATE_CRT}
#spring.ssl.bundle.pem.mybundle.truststore.certificate=${CA_BUNDLE}
#server.ssl.bundle=mybundle
server.port=8443