spring.profiles.default=prod

# set in enviroment for development
spring.profiles.active=${SPRING_PROFILES_ACTIVE:}

#this property is default, need to check
#hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy