# Read values from environment
spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=${DB_DRIVER_CLASS_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

######
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.continue-on-error=false

#-----settings for: to show sql queries + "to beautify"
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#-------------------------------------------------------
spring.datasource.hikari.data-source-properties.useUnicode=true
spring.datasource.hikari.data-source-properties.characterEncoding=UTF-8

#SLL connection properties
#### hosting server on railway.app is handling HTTPS by its own, so only "server.port" property is needed
#spring.ssl.bundle.pem.mybundle.keystore.certificate=${PRIVATE_KEY}
#spring.ssl.bundle.pem.mybundle.keystore.private-key=${CERTIFICATE_CRT}
#spring.ssl.bundle.pem.mybundle.truststore.certificate=${CA_BUNDLE}
#server.ssl.bundle=mybundle
server.port=8443